# Generated by Django 5.2.4 on 2025-08-04 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_ended', models.BooleanField()),
                ('reason_end', models.TextField()),
                ('context_matched', models.BooleanField()),
                ('reason_context', models.TextField()),
                ('gpt_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='aiservice.evaluationsession')),
            ],
        ),
        migrations.DeleteModel(
            name='EvaluationResult',
        ),
    ]
